"""empty message

Revision ID: dcd9991e4c21
Revises: 768bebeec8e6
Create Date: 2020-01-24 16:26:34.151257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd9991e4c21'
down_revision = '768bebeec8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=1000), nullable=False),
    sa.Column('second_name', sa.String(length=1000), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=False),
    sa.Column('occupation', sa.String(length=1000), nullable=False),
    sa.Column('birth_day', sa.DateTime(), nullable=False),
    sa.Column('skills', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
